### ISSUE TITLE
Bug: Wrong address when Ethereum dapps

### ISSUE THREAD

**Issue by lukaslevert** [brave/wallet-standard-brave#28]
I've noticed a few times when connecting to an Ethereum app and selecting the wallet address I want to use, the connection initially connects the default account even when it's not the active account in the wallet. I then need to manually switch my account, disconnect, and reconnect.

**Comment by darkdh** [comment]
Invalid issue in this repo, please open one in https://github.com/brave/brave-browser. Also it has been solved in https://github.com/brave/brave-browser/issues/30802
