### ISSUE TITLE
Add support for XinFin - XDC Network.

### ISSUE THREAD

**Issue by vrushalipanchal** [brave/wallet-standard-brave#35]
Hello BraveWallet Team,

Please add support for XinFin - XDC Network!

**XDC Network** is an **EVM-compatible Layer 1 Network.** A highly optimized, bespoke fork of Ethereum, the XDC Network reaches consensus through a delegated proof-of-stake (XDPoS) mechanism, which allows for two-second transaction time, near zero gas fees, and a high number of transactions per second. Secure, scalable, and highly efficient, the XDC Network powers a wide range of novel blockchain use cases and provides state-of-the-art infrastructure for enterprise-grade blockchain applications and real-world asset tokenization.

**Official Website:** https://xinfin.org/
**XDC Network:** https://xdc.network/home
**GitHub:** https://github.com/XinFinOrg/XDPoSChain
**CMC:** https://coinmarketcap.com/currencies/xinfin-network/
**Circulating Supply:** https://explorerapi.xinfin.network/publicAPI?module=balance&action=getcirculatingsupply
**Total Supply:** https://explorerapi.xinfin.network/publicAPI?module=balance&action=totalXDC
**Exchange Listing Resource:** https://xinfin.org/exchange-listing-resource

------------------------------

### Network Details for Mainnet
**Network ID:** 50

**RPC:**
- https://rpc.xinfin.network/
- https://erpc.xinfin.network/
- https://arpc.xinfin.network/
- https://earpc.xinfin.network/
- https://xdc.public-rpc.com/

**eRPC:**
https://erpc.xdcrpc.com/
https://erpc.xinfin.network/

**Explorer:**
- https://xdcscan.io/
- https://xdc.blocksscan.io/
- https://explorer.xinfin.network/
- https://xdc.network/

**Web Socket:**
- wss://ws.xinfin.network
- wss://ews.xinfin.network
- wss://aws.xinfin.network
- wss://eaws.xinfin.network

-----------------------------------------

### Network Details for Apothem Network
**Network ID:** 51

**RPC:**
- https://rpc.apothem.network/
- https://apothem.xdcrpc.com/

**eRPC:**
- https://erpc.apothem.network/

**Faucet:**
- https://faucet.apothem.network/
- https://faucet.blocksscan.io/

**Explorer:**
- https://apothem.xdcscan.io/
- https://apothem.blocksscan.io/
- https://explorer.apothem.network/

**Web Socket:**
- wss://ws.apothem.network/ws

-----------------------------------------

### Technical Community Support available at:
**Telegram Community:** https://t.me/XinFinDevelopers
**Slack Community:** https://xinfin-public.slack.com/messages/CELR2M831/
**Slack Invitation Link:** https://launchpass.com/xinfin-public
**Technical help Resource:** http://howto.xinfin.org/

Hope you will revert soon, Thank You!

**Comment by kdenhartog** [comment]
Since this network is EVM compatable then users can already opt into supporting the network by using `brave://settings/wallet/networks`. When a user clicks `add` they can search for your network and find it already. 
![Screenshot 2023-10-20 at 2 26 30 AM](https://github.com/brave/wallet-standard-brave/assets/23125059/4aa0ba22-fe2f-4d11-8cc2-076d7a165fad)

This seems like an unactionable as these networks are already listed on https://chainlist.org/

**Comment by vrushalipanchal** [comment]
Thank you for your prompt response, @kdenhartog,

I kindly request an update for the logo and asset name for XDC Network:

1. Instead of "XinFin - XDC on XinFin XDC Network," it should be "XDC - XDC on XDC Network."
![BraveXDCMainnet](https://github.com/brave/wallet-standard-brave/assets/39384359/851b4374-e2fa-4523-824b-81407a261780)

For XDC Apothem Network, It should be "TXDC - TXDC on XDC Apothem Network"
![image](https://github.com/brave/wallet-standard-brave/assets/39384359/2bcab774-6bcc-4274-8ef3-de3e61b358d9)

2. Please find the attached logo link to update the Logo in the Brave Wallet. (https://altcoinsbox.com/xdc-logo-download-xdc-network-logo-svg-png-ai-eps/)

Your assistance is greatly appreciated. Thank you!

**Comment by kdenhartog** [comment]
You'll need to update these within chainlist.org then which is where this information is pulled from. We don't maintain a separate list for this.

**Comment by vrushalipanchal** [comment]
Noted. Thank you!
