### ISSUE TITLE
signTransaction breaks with multiple versioned transaction

### ISSUE THREAD

**Issue by crispheaney** [brave/wallet-standard-brave#36]
If you pass multiple versioned transactions to `signTransaction`, it assumes they are legacy, causing the function to throw an error: https://github.com/brave/wallet-standard-brave/blob/master/src/wallet.ts#L237

It looks like it was just missed in the commit to enable versioned tx: https://github.com/brave/wallet-standard-brave/commit/b0801b7cfd73d5821852b66c92fc054b603ee48b

I think if you just change `Transaction.from(transaction)` -> `VersionedTransaction.deserialize(transaction)` it will fix it

I am happy to open a pr if my assessment is correct!

**Comment by yrliou** [comment]
Thanks a lot for the contribution, I will review the PR shortly!

**Comment by lukecaan** [comment]
Any update on this @yrliou ?

**Comment by yrliou** [comment]
@lukecaan Sorry I forgot to get back to this, thanks for the ping, I'll test it out and handle the rest from here today.

**Comment by yrliou** [comment]
@lukecaan @crispheaney is there an live example I can use in the test plan?

**Comment by yrliou** [comment]
Browser update issue: https://github.com/brave/brave-browser/issues/34672
Changes will be in effect on Nightly once it's merged into master, and Beta and Release once we uplifted the bump.
